name: Metrics
on:
  push:
  workflow_dispatch:
  schedule: [{cron: "0 0 * * *"}]

jobs:
  metrics:
    runs-on: ubuntu-latest
    
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.svg
          base: activity, community, repositories, metadata
          timezone: America/Detroit
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_lines: yes
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}