name: Metrics
on:
  workflow_dispatch:
  schedule: [{cron: "0 0 * * *"}]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: tetra-fox
          template: classic
          base: activity, repositories
          config_animated: yes
          config_timezone: America/Detroit
          plugin_activity: no
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_threshold: 0.2%
          
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          SHOW_TOTAL: true
