name: Update profile
on:
  workflow_dispatch:
  schedule: [{cron: "0 0 * * *"}]

jobs:
  metrics:
    runs-on: ubuntu-latest
    
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.svg
          committer_message: Update metrics
          base: activity, community, repositories, metadata
          base_indepth: true
          plugin_lines: true
          plugin_traffic: true
          plugin_languages: true
          plugin_languages_indepth: true
          plugin_languages_ignored: html, css, tex, less, dockerfile, batchfile, makefile, qmake, lex, cmake, shell, gnuplot, visual basic, javascript
          plugin_languages_details: lines, percentage
          plugin_languages_aliases: RenderScript:Rust # why does this happen
          plugin_wakatime: true
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}